save_name = "sweep_03"
num_particles = 4
history_len = 5
feature_type = "delta_mag"

[train]
epochs = 200
n_steps = 5
lr = 1e-4
steps_per_epoch = 2
energy_threshold = 2e-4
wandb = true

[simulate]
steps = 500
